name: Compare to meta-repo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compare:
    uses: Nexus-Mods/NexusMods.App.Meta/.github/workflows/compare-to-meta.yaml@fc9c9eae43a7c70eaa4d66b3717cd9cd35cc2bbb
